### PR TITLE
Move client, docs, server into separate packages (Implementation 2)

### PR DESCRIPTION
**Pull request by Krasjet**
In this alternative implementation, `servant-rawm` defines the API and other packages defines the implementation.

### CODE REVIEW

**Comment by Krasjet** [comment]
A sample upgrade can be found [here](https://github.com/Krasjet/karasu/compare/86f7cbc...3d757c0), the change in the code base is very minimal.

**Review by Krasjet — COMMENTED** [review]
`cabal sdist` is able to handle symlinks correctly and copy over the actual license files, so it's not necessary to duplicate licenses.

**Comment by cdepillabout** [comment]
@Krasjet Thanks for sending this PR!

I added some commits that change a few small things and move some things around.  Could you do a quick review of these commits?  Please feel free to fix up any problems you find.

I separated the examples and tests to a separate `servant-rawm-examples-and-tests` package.  This is slightly easier than having the `servant-rawm` package have circular dependencies.

If everything looks good, I'll go ahead and merge this in, and release these packages to Hackage.

> cabal sdist is able to handle symlinks correctly and copy over the actual license files, so it's not necessary to duplicate licenses.

Ah, nice tip.  I wasn't sure if this worked, so I just duplicated them instead of trying to figure out.  However, if you want to change this back, please feel free.

Also, if you'd like to add your name/email to the maintainer and/or author field of the .cabal files, please go ahead.

--------------------------------------------

I've added you as a collaborator here on GitHub.  Please feel free to review PRs, merge things in, etc in the future.

Also, if you let me know your username on Hackage, I will add you as a maintainer for these packages on Hackage after I upload them.

**Comment by Krasjet** [comment]
Thanks for cleaning everything up. It looks good to me. I think you can merge this in and push the update to Hackage now :).

**Comment by cdepillabout** [comment]
I've released these to Hackage:

- https://hackage.haskell.org/package/servant-rawm-1.0.0.0
- https://hackage.haskell.org/package/servant-rawm-client-1.0.0.0
- https://hackage.haskell.org/package/servant-rawm-docs-1.0.0.0
- https://hackage.haskell.org/package/servant-rawm-server-1.0.0.0

@Krasjet If you let me know your username on Hackage, I can add you as a maintainer for these packages.  This will let you push new versions to Hackage in the future.

**Comment by Krasjet** [comment]
It's the same as my GitHub username.

**Comment by cdepillabout** [comment]
@Krasjet Thanks.  I've added you as a maintainer to those packages on Hackage.

Please feel free to make releases in the future, especially if I am not responding to PRs/issues for some reason.

**Pull request merged**
